import re

llasm_include_re = re.compile(r'^include\s+(\S+)\r?$', re.M)

def llasmfile_scan(node, env, path):
    contents = node.get_text_contents()
    includes = llasm_include_re.findall(contents)
    return includes

llasmscan = Scanner(function = llasmfile_scan,
                    skeys = ['.llasm'],
                    recursive = True)

SourceFileScanner.add_scanner('.llasm', llasmscan)


Import('device', 'env')

obj = env.Object(Glob('*.c'))

for llasm_file in Glob('*.llasm', strings = True):
    obj += env.llasm(llasm_file)

Return('obj')

