#
#  Copyright (C) 2016 Roman Pauer
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to deal in
#  the Software without restriction, including without limitation the rights to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
#  of the Software, and to permit persons to whom the Software is furnished to do
#  so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.
#

udis86_path = './udis86-1.6/'

# set help text
vars = Variables('custom.py')
vars.Add(BoolVariable('debug', 'Set to build debug version', 0))
env = Environment(variables = vars)
Help(vars.GenerateHelpText(env))
debug = env['debug']

# default settings
env = Environment(CCFLAGS      = '-O2 -Wall',
                  CPPPATH      = '.',
                  INCPREFIX    = '-I' + udis86_path,
                  LIBPATH      = 'libudis86',
                  LIBDIRPREFIX = '-L' + udis86_path,
                  LINKFLAGS    = '',
                  LIBS         = ['udis86', 'Judy']
                 )

# debug settings
if debug:
    env.Append(CCFLAGS = ' -g -D__DEBUG__')

env.Program('SR.exe', Glob('*.c'))
